In [5]:
import numpy as np
import pandas as pd
from itertools import product
import os
from tqdm import tqdm

In [6]:
%%time
eq_info = np.load('/media/Data_storage/Mobilcell/DayEventData/output_daily-events-data_20190311.npy')
eq_info.shape

CPU times: user 0 ns, sys: 665 ms, total: 665 ms
Wall time: 668 ms


(27988670, 9)

In [4]:
eq_to_map = eq_info[ np.in1d( eq_info[:,1], np.arange(600, 615) ) ]
eq_to_map.shape, eq_to_map[:3]

((497526, 9),
 array([[     7,    603, 223629, 659898, 225589, 661267,      3,   2391,
             13],
        [    34,    600, 198761, 506523, 197126, 505540,      5,   1907,
              6],
        [    34,    605, 197126, 505540, 198761, 506523,      6,   1907,
              5]], dtype=int32))

In [14]:
np.unique( eq_to_map[:,2:6], return_counts=True, axis=0)[0].shape

(518865, 4)

In [18]:
np.histogram( np.unique( eq_to_map[:,2:6], return_counts=True, axis=0)[1] )

(array([516925,   1508,    278,     82,     38,     16,      7,      7,
             1,      3]),
 array([ 1. , 10.1, 19.2, 28.3, 37.4, 46.5, 55.6, 64.7, 73.8, 82.9, 92. ]))

### TODO:
- investigate polygon grid
- fix polygon grid somehow beyond days, towers should be at the same pos
- maybe do it in post proc phase with np.isclose and threshold
- check polygons for technology (2G, 3G, 4G), maybe embed data into multiple layers?


- check mobilecell data for different kind of events (data, sms, call)
- which is most problematic?


- can do great improvement:
    * match polygon grid with openstreetmap
    * movements should be along roads, trainlines, etc.
    * might be good to interpolate only events shorter that 60 minutes


- goal: 
    * same network node distribution, same positions, but different links
    * graph links evolving in time -> encoder embedding, LSTM or RNN to pred, then tranform back or look for link prediction algorithms

Some sources:

- https://github.com/facebookresearch/SEAL_OGB
- https://ogb.stanford.edu/docs/linkprop/#ogbl-ppa
- https://ogb.stanford.edu/docs/leader_linkprop/
